name: food_planner
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  shared_preferences:
  flutter_screenutil:
  flutter_svg:
  flutter_bloc:
  bloc:
  get_it:
  dartz:
  intl:
  flutter_native_splash:
  dio:
  flutter_styled_toast:
  cached_network_image:
  shimmer:
  smooth_page_indicator:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
